const DISCOVERY_DATA = [
  { label: `Easy Content Accessibility`, category: null },
  { label: `Overall Utilization`, category: null },
  {
    label: `calculates students time online`,
    category: `Overall Utilization`,
  },
  {
    label: `notify's students progress`,
    category: `Overall Utilization`,
  },
  {
    label: `reminders of tasks overdue`,
    category: `Overall Utilization`,
  },
  {
    label: `reminders of task due`,
    category: `Overall Utilization`,
  },
  {
    label: `reports completion of tasks`,
    category: `Overall Utilization`,
  },
  { label: `Seamless Intergration`, category: null },
  { label: `Data Import and Export`, category: null },
  { label: `Clean and Userfriendly Browser `, category: null },
  { label: `Single Sign on`, category: null },
  { label: `Easy User Experience`, category: null },
  { label: `Email Notifcation`, category: null },
  { label: `teacher`, category: `Email Notifcation` },
  { label: `student`, category: `Email Notifcation` },
  { label: `parent`, category: `Email Notifcation` },
  { label: `Interface Capability`, category: null },
  { label: `Intuitive Dashboards`, category: null },
  { label: `assignments`, category: `Intuitive Dashboards` },
  { label: `grades`, category: `Intuitive Dashboards` },
  { label: `courses`, category: `Intuitive Dashboards` },
  { label: `adminstration`, category: `Intuitive Dashboards` },
  { label: `teacher`, category: `Intuitive Dashboards` },
  { label: `parent`, category: `Intuitive Dashboards` },
  { label: `student`, category: `Intuitive Dashboards` },
  { label: `Training links for students`, category: null },
  {
    label: `Moby Max `,
    category: `Training links for students`,
  },
  {
    label: `Class Dojo`,
    category: `Training links for students`,
  },
  {
    label: `ReadWrite Think`,
    category: `Training links for students`,
  },
  {
    label: `MathGames`,
    category: `Training links for students`,
  },
  {
    label: `adobe reader`,
    category: `Training links for students`,
  },
  { label: `Easy User Interface`, category: null },
  { label: `Quick and easy`, category: `Easy User Interface` },
  { label: `work flows`, category: `Easy User Interface` },
  { label: `Action Insights`, category: null },
  {
    label: `data that matters useful`,
    category: `Action Insights`,
  },
  {
    label: `personalized interactons/hands raised`,
    category: `Action Insights`,
  },
  {
    label: `Interactive postive rewards`,
    category: `Action Insights`,
  },
  { label: `Teacher Resources`, category: null },
  { label: `Jamboard`, category: `Teacher Resources` },
  { label: `Teachers 1st`, category: `Teacher Resources` },
  { label: `Clever`, category: `Teacher Resources` },
  { label: `Edmodo`, category: `Teacher Resources` },
  { label: `Khan academy`, category: `Teacher Resources` },
  { label: `Teacher Tools`, category: null },
  { label: `*Automated Grading`, category: `Teacher Tools` },
  { label: `Reporting System`, category: null },
  { label: `time spent online`, category: `Reporting System` },
  { label: `assignments due`, category: `Reporting System` },
  { label: `assignments pastdue`, category: `Reporting System` },
  {
    label: `assignments coming due`,
    category: `Reporting System`,
  },
  { label: `test results`, category: `Reporting System` },
  { label: `grade book`, category: `Reporting System` },
  { label: `Reward Systems`, category: null },
  { label: `integrated I.E -Dojo`, category: `Reward Systems` },
  { label: `Recording `, category: null },
  { label: `platform`, category: `Recording ` },
  { label: `computer`, category: `Recording ` },
  { label: `Whiteboard Capacties`, category: null },
  { label: `Chat Capabilities`, category: null },
  { label: `Document Portals storage`, category: null },
  { label: `limited `, category: `Document Portals storage` },
  { label: `unlimited`, category: `Document Portals storage` },
  { label: `App portal intergrations`, category: null },
  { label: `Epic`, category: `App portal intergrations` },
  { label: `Quick Math`, category: `App portal intergrations` },
  { label: `Brainpop`, category: `App portal intergrations` },
  {
    label: `Youtube kids`,
    category: `App portal intergrations`,
  },
  { label: `Pearadome`, category: `App portal intergrations` },
  { label: `Parent Resources`, category: null },
  { label: `remind`, category: `Parent Resources` },
  { label: `seesaw`, category: `Parent Resources` },
  { label: `parent square`, category: `Parent Resources` },
  { label: `BrainPop`, category: `Parent Resources` },
  {
    label: `Practice tests K-12th`,
    category: `Parent Resources`,
  },
  { label: `Teacher Tube`, category: `Parent Resources` },
  { label: `Learn Zillion`, category: `Parent Resources` },
  { label: `Training  links for parents`, category: null },
  {
    label: `Open-and-go free content `,
    category: `Training  links for parents`,
  },
  {
    label: `Ready now online instruction`,
    category: `Training  links for parents`,
  },
  {
    label: ` Learning options for summer`,
    category: `Training  links for parents`,
  },
  { label: `K-12`, category: null },
  { label: `K-8th`, category: null },
  { label: `One on One Instruction`, category: null },
  { label: `Group Instruction`, category: null },
  { label: `Media Player`, category: null },
  { label: `youtube`, category: `Media Player` },
  { label: `windows media player`, category: `Media Player` },
  { label: `Castify`, category: `Media Player` },
  { label: `imovie`, category: `Media Player` },
  { label: `Deployment Type of SIS`, category: null },
  { label: `cloud-based `, category: `Deployment Type of SIS` },
  { label: `On-premise`, category: `Deployment Type of SIS` },
  {
    label: `Compatible with all operating systems`,
    category: null,
  },
  {
    label: `windows`,
    category: `Compatible with all operating systems`,
  },
  {
    label: `IOS`,
    category: `Compatible with all operating systems`,
  },
  { label: `Mobile Ready`, category: null },
  { label: `mobile apple device`, category: `Mobile Ready` },
  { label: `android`, category: `Mobile Ready` },
  { label: `Free Demos`, category: null },
];
export default DISCOVERY_DATA;
