const DISCOVERY_DATA = [
  { id: `1`, label: `Easy Content Accessibility`, category: null },
  { id: `2`, label: `Overall Utilization`, category: null },
  {
    id: `3`,
    label: `calculates students time online`,
    category: `Overall Utilization`,
  },
  {
    id: `4`,
    label: `notify's students progress`,
    category: `Overall Utilization`,
  },
  {
    id: `5`,
    label: `reminders of tasks overdue`,
    category: `Overall Utilization`,
  },
  { id: `6`, label: `reminders of task due`, category: `Overall Utilization` },
  {
    id: `7`,
    label: `reports completion of tasks`,
    category: `Overall Utilization`,
  },
  { id: `8`, label: `Seamless Intergration`, category: null },
  { id: `9`, label: `Data Import/Export`, category: null },
  { id: `10`, label: `Clean and Userfriendly Browser `, category: null },
  { id: `11`, label: `Single Sign on`, category: null },
  { id: `12`, label: `Easy User Experience`, category: null },
  { id: `13`, label: `Email Notifcation`, category: null },
  { id: `14`, label: `teacher`, category: `Email Notifcation` },
  { id: `15`, label: `student`, category: `Email Notifcation` },
  { id: `16`, label: `parent`, category: `Email Notifcation` },
  { id: `17`, label: `Interface Capability`, category: null },
  { id: `18`, label: `Intuitive Dashboards`, category: null },
  { id: `19`, label: `assignments`, category: `Intuitive Dashboards` },
  { id: `20`, label: `grades`, category: `Intuitive Dashboards` },
  { id: `21`, label: `courses`, category: `Intuitive Dashboards` },
  { id: `22`, label: `adminstration`, category: `Intuitive Dashboards` },
  { id: `23`, label: `teacher`, category: `Intuitive Dashboards` },
  { id: `24`, label: `parent`, category: `Intuitive Dashboards` },
  { id: `25`, label: `student`, category: `Intuitive Dashboards` },
  { id: `26`, label: `Training links for students`, category: null },
  { id: `27`, label: `Moby Max `, category: `Training links for students` },
  { id: `28`, label: `Class Dojo`, category: `Training links for students` },
  {
    id: `29`,
    label: `ReadWrite Think`,
    category: `Training links for students`,
  },
  { id: `30`, label: `MathGames`, category: `Training links for students` },
  { id: `31`, label: `adobe reader`, category: `Training links for students` },
  { id: `32`, label: `Easy User Interface`, category: null },
  { id: `33`, label: `Quick and easy`, category: `Easy User Interface` },
  { id: `34`, label: `work flows`, category: `Easy User Interface` },
  { id: `35`, label: `Action Insights`, category: null },
  { id: `36`, label: `data that matters useful`, category: `Action Insights` },
  {
    id: `37`,
    label: `personalized interactons/hands raised`,
    category: `Action Insights`,
  },
  {
    id: `38`,
    label: `Interactive postive rewards`,
    category: `Action Insights`,
  },
  { id: `39`, label: `Teacher Resources`, category: null },
  { id: `40`, label: `Jamboard`, category: `Teacher Resources` },
  { id: `41`, label: `Teachers 1st`, category: `Teacher Resources` },
  { id: `42`, label: `Clever`, category: `Teacher Resources` },
  { id: `43`, label: `Edmodo`, category: `Teacher Resources` },
  { id: `44`, label: `Khan academy`, category: `Teacher Resources` },
  { id: `45`, label: `Teacher Tools`, category: null },
  { id: `46`, label: `*Automated Grading`, category: `Teacher Tools` },
  { id: `47`, label: `Reporting System`, category: null },
  { id: `48`, label: `time spent online`, category: `Reporting System` },
  { id: `49`, label: `assignments due`, category: `Reporting System` },
  { id: `50`, label: `assignments pastdue`, category: `Reporting System` },
  { id: `51`, label: `assignments coming due`, category: `Reporting System` },
  { id: `52`, label: `test results`, category: `Reporting System` },
  { id: `53`, label: `grade book`, category: `Reporting System` },
  { id: `54`, label: `Reward Systems`, category: null },
  { id: `55`, label: `integrated I.E -Dojo`, category: `Reward Systems` },
  { id: `56`, label: `Recording `, category: null },
  { id: `57`, label: `platform`, category: `Recording ` },
  { id: `58`, label: `computer`, category: `Recording ` },
  { id: `59`, label: `Whiteboard Capacties`, category: null },
  { id: `60`, label: `Chat Capabilities`, category: null },
  { id: `61`, label: `Document Portals storage`, category: null },
  { id: `62`, label: `limited `, category: `Document Portals storage` },
  { id: `63`, label: `unlimited`, category: `Document Portals storage` },
  { id: `64`, label: `App portal intergrations`, category: null },
  { id: `65`, label: `Epic`, category: `App portal intergrations` },
  { id: `66`, label: `Quick Math`, category: `App portal intergrations` },
  { id: `67`, label: `Brainpop`, category: `App portal intergrations` },
  { id: `68`, label: `Youtube kids`, category: `App portal intergrations` },
  { id: `69`, label: `Pearadome`, category: `App portal intergrations` },
  { id: `70`, label: `Parent Resources`, category: null },
  { id: `71`, label: `remind`, category: `Parent Resources` },
  { id: `72`, label: `seesaw`, category: `Parent Resources` },
  { id: `73`, label: `parent square`, category: `Parent Resources` },
  { id: `74`, label: `BrainPop`, category: `Parent Resources` },
  { id: `75`, label: `Practice tests K-12th`, category: `Parent Resources` },
  { id: `76`, label: `Teacher Tube`, category: `Parent Resources` },
  { id: `77`, label: `Learn Zillion`, category: `Parent Resources` },
  { id: `78`, label: `Training  links for parents`, category: null },
  {
    id: `79`,
    label: `Open-and-go free content `,
    category: `Training  links for parents`,
  },
  {
    id: `80`,
    label: `Ready now online instruction`,
    category: `Training  links for parents`,
  },
  {
    id: `81`,
    label: ` Learning options for summer`,
    category: `Training  links for parents`,
  },
  { id: `82`, label: `K-12`, category: null },
  { id: `83`, label: `K-8th`, category: null },
  { id: `84`, label: `One on One Instruction`, category: null },
  { id: `85`, label: `Group Instruction`, category: null },
  { id: `86`, label: `Media Player`, category: null },
  { id: `87`, label: `youtube`, category: `Media Player` },
  { id: `88`, label: `windows media player`, category: `Media Player` },
  { id: `89`, label: `Castify`, category: `Media Player` },
  { id: `90`, label: `imovie`, category: `Media Player` },
  { id: `91`, label: `Deployment Type of SIS`, category: null },
  { id: `92`, label: `cloud-based `, category: `Deployment Type of SIS` },
  { id: `93`, label: `On-premise`, category: `Deployment Type of SIS` },
  { id: `94`, label: `Compatible with all operating systems`, category: null },
  {
    id: `95`,
    label: `windows`,
    category: `Compatible with all operating systems`,
  },
  { id: `96`, label: `IOS`, category: `Compatible with all operating systems` },
  { id: `97`, label: `Mobile Ready`, category: null },
  { id: `98`, label: `mobile apple device`, category: `Mobile Ready` },
  { id: `99`, label: `android`, category: `Mobile Ready` },
  { id: `100`, label: `Free Demos`, category: null },
];
export default DISCOVERY_DATA;
