const DISCOVERY_DATA = [
  {
    formId: `1`,
    label: `Easy Content Accessibility`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `2`,
    label: `Overall Utilization`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `3`,
    label: `calculates students time online`,
    categoryId: `2`,
    categoryLabel: `Overall Utilization`,
  },
  {
    formId: `4`,
    label: `notify's students progress`,
    categoryId: `2`,
    categoryLabel: `Overall Utilization`,
  },
  {
    formId: `5`,
    label: `reminders of tasks overdue`,
    categoryId: `2`,
    categoryLabel: `Overall Utilization`,
  },
  {
    formId: `6`,
    label: `reminders of task due`,
    categoryId: `2`,
    categoryLabel: `Overall Utilization`,
  },
  {
    formId: `7`,
    label: `reports completion of tasks`,
    categoryId: `2`,
    categoryLabel: `Overall Utilization`,
  },
  {
    formId: `8`,
    label: `Seamless Intergration`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `9`,
    label: `Data Import/Export`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `10`,
    label: `Clean and Userfriendly Browser `,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `11`,
    label: `Single Sign on`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `12`,
    label: `Easy User Experience`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `13`,
    label: `Email Notifcation`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `14`,
    label: `teacher`,
    categoryId: `13`,
    categoryLabel: `Email Notifcation`,
  },
  {
    formId: `15`,
    label: `student`,
    categoryId: `13`,
    categoryLabel: `Email Notifcation`,
  },
  {
    formId: `16`,
    label: `parent`,
    categoryId: `13`,
    categoryLabel: `Email Notifcation`,
  },
  {
    formId: `17`,
    label: `Interface Capability`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `18`,
    label: `Intuitive Dashboards`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `19`,
    label: `assignments`,
    categoryId: `18`,
    categoryLabel: `Intuitive Dashboards`,
  },
  {
    formId: `20`,
    label: `grades`,
    categoryId: `18`,
    categoryLabel: `Intuitive Dashboards`,
  },
  {
    formId: `21`,
    label: `courses`,
    categoryId: `18`,
    categoryLabel: `Intuitive Dashboards`,
  },
  {
    formId: `22`,
    label: `adminstration`,
    categoryId: `18`,
    categoryLabel: `Intuitive Dashboards`,
  },
  {
    formId: `23`,
    label: `teacher`,
    categoryId: `18`,
    categoryLabel: `Intuitive Dashboards`,
  },
  {
    formId: `24`,
    label: `parent`,
    categoryId: `18`,
    categoryLabel: `Intuitive Dashboards`,
  },
  {
    formId: `25`,
    label: `student`,
    categoryId: `18`,
    categoryLabel: `Intuitive Dashboards`,
  },
  {
    formId: `26`,
    label: `Training links for students`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `27`,
    label: `Moby Max `,
    categoryId: `26`,
    categoryLabel: `Training links for students`,
  },
  {
    formId: `28`,
    label: `Class Dojo`,
    categoryId: `26`,
    categoryLabel: `Training links for students`,
  },
  {
    formId: `29`,
    label: `ReadWrite Think`,
    categoryId: `26`,
    categoryLabel: `Training links for students`,
  },
  {
    formId: `30`,
    label: `MathGames`,
    categoryId: `26`,
    categoryLabel: `Training links for students`,
  },
  {
    formId: `31`,
    label: `adobe reader`,
    categoryId: `26`,
    categoryLabel: `Training links for students`,
  },
  {
    formId: `32`,
    label: `Easy User Interface`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `33`,
    label: `Quick and easy`,
    categoryId: `32`,
    categoryLabel: `Easy User Interface`,
  },
  {
    formId: `34`,
    label: `work flows`,
    categoryId: `32`,
    categoryLabel: `Easy User Interface`,
  },
  {
    formId: `35`,
    label: `Action Insights`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `36`,
    label: `data that matters useful`,
    categoryId: `35`,
    categoryLabel: `Action Insights`,
  },
  {
    formId: `37`,
    label: `personalized interactons/hands raised`,
    categoryId: `35`,
    categoryLabel: `Action Insights`,
  },
  {
    formId: `38`,
    label: `Interactive postive rewards`,
    categoryId: `35`,
    categoryLabel: `Action Insights`,
  },
  {
    formId: `39`,
    label: `Teacher Resources`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `40`,
    label: `Jamboard`,
    categoryId: `39`,
    categoryLabel: `Teacher Resources`,
  },
  {
    formId: `41`,
    label: `Teachers 1st`,
    categoryId: `39`,
    categoryLabel: `Teacher Resources`,
  },
  {
    formId: `42`,
    label: `Clever`,
    categoryId: `39`,
    categoryLabel: `Teacher Resources`,
  },
  {
    formId: `43`,
    label: `Edmodo`,
    categoryId: `39`,
    categoryLabel: `Teacher Resources`,
  },
  {
    formId: `44`,
    label: `Khan academy`,
    categoryId: `39`,
    categoryLabel: `Teacher Resources`,
  },
  {
    formId: `45`,
    label: `Teacher Tools`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `46`,
    label: `*Automated Grading`,
    categoryId: `45`,
    categoryLabel: `Teacher Tools`,
  },
  {
    formId: `47`,
    label: `Reporting System`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `48`,
    label: `time spent online`,
    categoryId: `47`,
    categoryLabel: `Reporting System`,
  },
  {
    formId: `49`,
    label: `assignments due`,
    categoryId: `47`,
    categoryLabel: `Reporting System`,
  },
  {
    formId: `50`,
    label: `assignments pastdue`,
    categoryId: `47`,
    categoryLabel: `Reporting System`,
  },
  {
    formId: `51`,
    label: `assignments coming due`,
    categoryId: `47`,
    categoryLabel: `Reporting System`,
  },
  {
    formId: `52`,
    label: `test results`,
    categoryId: `47`,
    categoryLabel: `Reporting System`,
  },
  {
    formId: `53`,
    label: `grade book`,
    categoryId: `47`,
    categoryLabel: `Reporting System`,
  },
  {
    formId: `54`,
    label: `Reward Systems`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `55`,
    label: `integrated I.E -Dojo`,
    categoryId: `54`,
    categoryLabel: `Reward Systems`,
  },
  { formId: `56`, label: `Recording `, categoryId: null, categoryLabel: null },
  {
    formId: `57`,
    label: `platform`,
    categoryId: `56`,
    categoryLabel: `Recording `,
  },
  {
    formId: `58`,
    label: `computer`,
    categoryId: `57`,
    categoryLabel: `platform`,
  },
  {
    formId: `59`,
    label: `Whiteboard Capacties`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `60`,
    label: `Chat Capabilities`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `61`,
    label: `Document Portals storage`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `62`,
    label: `limited `,
    categoryId: `61`,
    categoryLabel: `Document Portals storage`,
  },
  {
    formId: `63`,
    label: `unlimited`,
    categoryId: `61`,
    categoryLabel: `Document Portals storage`,
  },
  {
    formId: `64`,
    label: `App portal intergrations`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `65`,
    label: `Epic`,
    categoryId: `64`,
    categoryLabel: `App portal intergrations`,
  },
  {
    formId: `66`,
    label: `Quick Math`,
    categoryId: `64`,
    categoryLabel: `App portal intergrations`,
  },
  {
    formId: `67`,
    label: `Brainpop`,
    categoryId: `64`,
    categoryLabel: `App portal intergrations`,
  },
  {
    formId: `68`,
    label: `Youtube kids`,
    categoryId: `64`,
    categoryLabel: `App portal intergrations`,
  },
  {
    formId: `69`,
    label: `Pearadome`,
    categoryId: `64`,
    categoryLabel: `App portal intergrations`,
  },
  {
    formId: `70`,
    label: `Parent Resources`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `71`,
    label: `remind`,
    categoryId: `70`,
    categoryLabel: `Parent Resources`,
  },
  {
    formId: `72`,
    label: `seesaw`,
    categoryId: `70`,
    categoryLabel: `Parent Resources`,
  },
  {
    formId: `73`,
    label: `parent square`,
    categoryId: `70`,
    categoryLabel: `Parent Resources`,
  },
  {
    formId: `74`,
    label: `BrainPop`,
    categoryId: `70`,
    categoryLabel: `Parent Resources`,
  },
  {
    formId: `75`,
    label: `Practice tests K-12th`,
    categoryId: `70`,
    categoryLabel: `Parent Resources`,
  },
  {
    formId: `76`,
    label: `Teacher Tube`,
    categoryId: `70`,
    categoryLabel: `Parent Resources`,
  },
  {
    formId: `77`,
    label: `Learn Zillion`,
    categoryId: `70`,
    categoryLabel: `Parent Resources`,
  },
  {
    formId: `78`,
    label: `Training  links for parents`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `79`,
    label: `Open-and-go free content `,
    categoryId: `78`,
    categoryLabel: `Training  links for parents`,
  },
  {
    formId: `80`,
    label: `Ready now online instruction`,
    categoryId: `78`,
    categoryLabel: `Training  links for parents`,
  },
  {
    formId: `81`,
    label: ` Learning options for summer`,
    categoryId: `78`,
    categoryLabel: `Training  links for parents`,
  },
  { formId: `82`, label: `K-12`, categoryId: null, categoryLabel: null },
  { formId: `83`, label: `K-8th`, categoryId: null, categoryLabel: null },
  {
    formId: `84`,
    label: `One on One Instruction`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `85`,
    label: `Group Instruction`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `86`,
    label: `Media Player`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `87`,
    label: `youtube`,
    categoryId: `86`,
    categoryLabel: `Media Player`,
  },
  {
    formId: `88`,
    label: `windows media player`,
    categoryId: `86`,
    categoryLabel: `Media Player`,
  },
  {
    formId: `89`,
    label: `Castify`,
    categoryId: `86`,
    categoryLabel: `Media Player`,
  },
  {
    formId: `90`,
    label: `imovie`,
    categoryId: `86`,
    categoryLabel: `Media Player`,
  },
  {
    formId: `91`,
    label: `Deployment Type of SIS`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `92`,
    label: `cloud-based `,
    categoryId: `91`,
    categoryLabel: `Deployment Type of SIS`,
  },
  {
    formId: `93`,
    label: `On-premise`,
    categoryId: `91`,
    categoryLabel: `Deployment Type of SIS`,
  },
  {
    formId: `94`,
    label: `Compatible with all operating systems`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `95`,
    label: `windows`,
    categoryId: `94`,
    categoryLabel: `Compatible with all operating systems`,
  },
  {
    formId: `96`,
    label: `IOS`,
    categoryId: `94`,
    categoryLabel: `Compatible with all operating systems`,
  },
  {
    formId: `97`,
    label: `Mobile Ready`,
    categoryId: null,
    categoryLabel: null,
  },
  {
    formId: `98`,
    label: `mobile apple device`,
    categoryId: `97`,
    categoryLabel: `Mobile Ready`,
  },
  {
    formId: `99`,
    label: `android`,
    categoryId: `97`,
    categoryLabel: `Mobile Ready`,
  },
  { formId: `100`, label: `Free Demos`, categoryId: null, categoryLabel: null },
];
export default DISCOVERY_DATA;
