const LMS_DATA = [
  {
    lms: 'Agilix',
    'Easy Content Accessibility': 0,
    'Overall Utilization': 1,
    'calculates students time online': 1,
    "notify's students progress": 1,
    'reminders of tasks overdue': 1,
    'reminders of task due': 1,
    'reports completion of tasks': 1,
    'Seamless Intergration': 0,
    'Data Import and Export': 1,
  },
  {
    lms: 'Blackboard',
    'Easy Content Accessibility': 1,
    'Overall Utilization': 1,
    'calculates students time online': 1,
    "notify's students progress": 1,
    'reminders of tasks overdue': 1,
    'reminders of task due': 1,
    'reports completion of tasks': 1,
    'Seamless Intergration': 1,
    'Data Import and Export': 1,
  },
  {
    lms: 'Blackbaud',
    'Easy Content Accessibility': 0,
    'Overall Utilization': 1,
    'calculates students time online': 1,
    "notify's students progress": 1,
    'reminders of tasks overdue': 1,
    'reminders of task due': 1,
    'reports completion of tasks': 1,
    'Seamless Intergration': 1,
    'Data Import and Export': 1,
  },
  {
    lms: 'Brightspace-D2L',
    'Easy Content Accessibility': 1,
    'Overall Utilization': 1,
    'calculates students time online': 1,
    "notify's students progress": 1,
    'reminders of tasks overdue': 1,
    'reminders of task due': 1,
    'reports completion of tasks': 1,
    'Seamless Intergration': 1,
    'Data Import and Export': 1,
  },
  {
    lms: 'Canvas',
    'Easy Content Accessibility': 1,
    'Overall Utilization': 1,
    'calculates students time online': 1,
    "notify's students progress": 1,
    'reminders of tasks overdue': 1,
    'reminders of task due': 1,
    'reports completion of tasks': 1,
    'Seamless Intergration': 1,
    'Data Import and Export': 1,
  },
  {
    lms: 'Chalkboard',
    'Easy Content Accessibility': 1,
    'Overall Utilization': 1,
    'calculates students time online': 1,
    "notify's students progress": 1,
    'reminders of tasks overdue': 1,
    'reminders of task due': 1,
    'reports completion of tasks': 1,
    'Seamless Intergration': 1,
    'Data Import and Export': 1,
  },
  {
    lms: 'Edmodo',
    'Easy Content Accessibility': 0,
    'Overall Utilization': 0,
    'calculates students time online': 0,
    "notify's students progress": 0,
    'reminders of tasks overdue': 0,
    'reminders of task due': 0,
    'reports completion of tasks': 0,
    'Seamless Intergration': 0,
    'Data Import and Export': 0,
  },
  {
    lms: 'Edsby',
    'Easy Content Accessibility': 0,
    'Overall Utilization': 0,
    'calculates students time online': 0,
    "notify's students progress": 0,
    'reminders of tasks overdue': 0,
    'reminders of task due': 0,
    'reports completion of tasks': 0,
    'Seamless Intergration': 0,
    'Data Import and Export': 0,
  },
  {
    lms: 'Edu-Happy',
    'Easy Content Accessibility': 0,
    'Overall Utilization': 1,
    'calculates students time online': 0,
    "notify's students progress": 0,
    'reminders of tasks overdue': 1,
    'reminders of task due': 1,
    'reports completion of tasks': 0,
    'Seamless Intergration': 0,
    'Data Import and Export': 1,
  },
  {
    lms: 'Infinite Campus',
    'Easy Content Accessibility': 0,
    'Overall Utilization': 0,
    'calculates students time online': 0,
    "notify's students progress": 0,
    'reminders of tasks overdue': 1,
    'reminders of task due': 1,
    'reports completion of tasks': 1,
    'Seamless Intergration': 0,
    'Data Import and Export': 1,
  },
  {
    lms: 'ItsLearning',
    'Easy Content Accessibility': 0,
    'Overall Utilization': 0,
    'calculates students time online': 0,
    "notify's students progress": 0,
    'reminders of tasks overdue': 0,
    'reminders of task due': 0,
    'reports completion of tasks': 0,
    'Seamless Intergration': 0,
    'Data Import and Export': 0,
  },
  {
    lms: 'LoveMySkool',
    'Easy Content Accessibility': 0,
    'Overall Utilization': 0,
    'calculates students time online': 0,
    "notify's students progress": 0,
    'reminders of tasks overdue': 0,
    'reminders of task due': 0,
    'reports completion of tasks': 0,
    'Seamless Intergration': 0,
    'Data Import and Export': 0,
  },
  {
    lms: 'Moodle',
    'Easy Content Accessibility': 1,
    'Overall Utilization': 1,
    'calculates students time online': 1,
    "notify's students progress": 1,
    'reminders of tasks overdue': 1,
    'reminders of task due': 1,
    'reports completion of tasks': 1,
    'Seamless Intergration': 0,
    'Data Import and Export': 1,
  },
  {
    lms: 'Open',
    'Easy Content Accessibility': 1,
    'Overall Utilization': 0,
    'calculates students time online': 0,
    "notify's students progress": 1,
    'reminders of tasks overdue': 1,
    'reminders of task due': 1,
    'reports completion of tasks': 1,
    'Seamless Intergration': 1,
    'Data Import and Export': 0,
  },
  {
    lms: 'Schoology',
    'Easy Content Accessibility': 1,
    'Overall Utilization': 1,
    'calculates students time online': 1,
    "notify's students progress": 1,
    'reminders of tasks overdue': 1,
    'reminders of task due': 1,
    'reports completion of tasks': 1,
    'Seamless Intergration': 0,
    'Data Import and Export': 1,
  },
  {
    lms: 'Synergy',
    'Easy Content Accessibility': 0,
    'Overall Utilization': 0,
    'calculates students time online': 0,
    "notify's students progress": 0,
    'reminders of tasks overdue': 0,
    'reminders of task due': 0,
    'reports completion of tasks': 0,
    'Seamless Intergration': 0,
    'Data Import and Export': 0,
  },
  {
    lms: 'Vedamo ',
    'Easy Content Accessibility': 1,
    'Overall Utilization': 1,
    'calculates students time online': 1,
    "notify's students progress": 1,
    'reminders of tasks overdue': 1,
    'reminders of task due': 1,
    'reports completion of tasks': 1,
    'Seamless Intergration': 0,
    'Data Import and Export': 1,
  },
];

export default LMS_DATA;
